[Skin]
    # Configuration for Modern JSON Skin
    
    [CheetahGenerator]
        # This section is used by the CheetahGenerator
        
        # The list of files to be generated.
        # Each entry is of the form 'template_file_name > generated_file_name'
        [[ToDate]]
            # Reports that show statistics "to date", such as day-to-date,
            # week-to-date, month-to-date, etc.
            [[[current]]]
                template = current.json.tmpl
            [[[trends]]]
                template = trends.json.tmpl

[CopyGenerator]
    # This section is used by the CopyGenerator

    # The list of files to be copied to the report directory
    copy_once = index.html, style.css, app.js, icons/*.svg

[Generators]
    # The list of generators to be run
    generator_list = weewx.cheetahgenerator.CheetahGenerator, weewx.reportengine.CopyGenerator
