[Skin]
    # Configuration for Aero Skin
    version = 1.2.1
    name = Aero
    
    [CheetahGenerator]
        # This section is used by the CheetahGenerator
        
        # The list of files to be generated.
        # Each entry is of the form 'template_file_name > generated_file_name'
        [[ToDate]]
            # Reports that show statistics "to date", such as day-to-date,
            # week-to-date, month-to-date, etc.
            [[[current]]]
                template = current.json.tmpl
                filename = data/current.json
            [[[trends]]]
                template = trends.json.tmpl
                filename = data/trends.json
            [[[today]]]
                template = daily.json.tmpl
                filename = data/today.json
            [[[week]]]
                template = week.json.tmpl
                filename = data/week.json
            [[[month]]]
                template = month.json.tmpl
                filename = data/month.json
        
    [[SummaryByDay]]
        [[[day]]]
            template = daily.json.tmpl
            filename = data/day-%Y-%m-%d.json

[CopyGenerator]
    # This section is used by the CopyGenerator

    # The list of files to be copied to the report directory
    copy_once = index.html, style.css, app.js, icons/*.svg

[Generators]
    # The list of generators to be run
    generator_list = weewx.cheetahgenerator.CheetahGenerator, weewx.reportengine.CopyGenerator
