[Skin]
    # Configuration for Aero Skin
    version = 2.1.2
    name = Aero
    
[CheetahGenerator]
    encoding = utf8
    
    # Reports that show statistics "to date", such as day-to-date,
    # week-to-date, month-to-date, etc.
    [[ToDate]]
        [[[current]]]
            template = templates/current.json.tmpl
            filename = data/current.json
            
        [[[trends]]]
            template = templates/trends.json.tmpl
            filename = data/trends.json
            
        # "Today" snapshot (convenience alias for current day)
        [[[today]]]
            template = templates/daily.json.tmpl
            filename = data/today.json
            
        # Current Week to Date
        [[[week]]]
            template = templates/week.json.tmpl
            filename = data/week.json
            
        # Current Month to Date
        [[[month]]]
            template = templates/month.json.tmpl
            filename = data/month.json

    # Daily Archive (History)
    [[SummaryByDay]]
        [[[day]]]
            template = templates/daily.json.tmpl
            filename = data/day-%Y-%m-%d.json

    # Monthly Archive (History)
    [[SummaryByMonth]]
        [[[month]]]
            template = templates/month.json.tmpl
            filename = data/month-%Y-%m.json

[CopyGenerator]
    # This section is used by the CopyGenerator

    # The list of files to be copied to the report    # Files to copy once
    copy_once = index.html, style.css, app.js, utils.js, charts.js, ui.js, state.js

[Generators]
    # The list of generators to be run
    generator_list = weewx.cheetahgenerator.CheetahGenerator, weewx.reportengine.CopyGenerator
